### PR TITLE
Improve HTML in single post style guide

### PR DESCRIPTION
**Pull request by jeremyfelt**

### CODE REVIEW

**Comment by jeremyfelt** [comment]
@slocker3 I updated the single post style guide with a bit more content (draft post from happyprimeweb.com) and I removed the sidebar. Feel free to play at will with the styles!

**Comment by slocker3** [comment]
@jeremyfelt I built onto this pull request.

- slight adjustment to `single-post.html` html
- adjusted headers and type for all pages

**Review by slocker3 — APPROVED** [review]
🌮 made some minor adjustmens

**Comment by slocker3** [comment]
Still need to figure out the HTML for the side-by-side photo/mini-profile section.

**Comment by slocker3** [comment]
@jeremyfelt #reviewmerge

**Pull request merged**
